export { default as AuthRouter } from './auth'
export { default as BandRouter } from './band-member'
export { default as SocialNetworkRouter } from './social-network'
export { default as UploadRouter } from './upload'
export { default as BandInfoRouter } from './band-info'
